/*
 * axctl - Hyprland config generator
 *
 * Generates hyprlang configuration syntax from universal config types.
 * Supports both legacy (hyprlang) and Lua (Hyprland >= 0.55) output formats.
 */

#include "ipc/hyprland/hyprland.h"
#include "ipc/config_types.h"
#include "ipc/colors.h"
#include "utils/strutil.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── hyprlang syntax generators ─────────────────────────────────────── */

char *hyprland_generate_appearance(const axctl_appearance_t *cfg)
{
    if (!cfg) return axctl_strdup("");
    char *out = axctl_strdup("# Appearance (generated by axctl)\n");

    if (cfg->gaps) {
        if (cfg->gaps->inner)
            axctl_str_append(&out, axctl_sprintf("general:gaps_in = %d\n", cfg->gaps->inner->value));
        if (cfg->gaps->outer)
            axctl_str_append(&out, axctl_sprintf("general:gaps_out = %d\n", cfg->gaps->outer->value));
    }

    if (cfg->border) {
        if (cfg->border->width)
            axctl_str_append(&out, axctl_sprintf("general:border_size = %d\n", cfg->border->width->value));
        if (cfg->border->active_color) {
            char *c = axctl_hyprland_color(cfg->border->active_color);
            char *line = axctl_sprintf("general:col.active_border = %s\n", c);
            axctl_str_append(&out, line);
            free(line); free(c);
        }
        if (cfg->border->inactive_color) {
            char *c = axctl_hyprland_color(cfg->border->inactive_color);
            char *line = axctl_sprintf("general:col.inactive_border = %s\n", c);
            axctl_str_append(&out, line);
            free(line); free(c);
        }
        if (cfg->border->rounding)
            axctl_str_append(&out, axctl_sprintf("decoration:rounding = %d\n", cfg->border->rounding->value));
    }

    if (cfg->opacity) {
        if (cfg->opacity->active)
            axctl_str_append(&out, axctl_sprintf("decoration:active_opacity = %.2f\n", cfg->opacity->active->value));
        if (cfg->opacity->inactive)
            axctl_str_append(&out, axctl_sprintf("decoration:inactive_opacity = %.2f\n", cfg->opacity->inactive->value));
    }

    if (cfg->blur) {
        if (cfg->blur->enabled)
            axctl_str_append(&out, axctl_sprintf("decoration:blur:enabled = %s\n",
                cfg->blur->enabled->value ? "true" : "false"));
        if (cfg->blur->size)
            axctl_str_append(&out, axctl_sprintf("decoration:blur:size = %d\n", cfg->blur->size->value));
        if (cfg->blur->passes)
            axctl_str_append(&out, axctl_sprintf("decoration:blur:passes = %d\n", cfg->blur->passes->value));
    }

    if (cfg->shadow) {
        if (cfg->shadow->enabled)
            axctl_str_append(&out, axctl_sprintf("decoration:shadow:enabled = %s\n",
                cfg->shadow->enabled->value ? "true" : "false"));
        if (cfg->shadow->size)
            axctl_str_append(&out, axctl_sprintf("decoration:shadow:range = %d\n", cfg->shadow->size->value));
        if (cfg->shadow->color) {
            char *c = axctl_hyprland_color(cfg->shadow->color);
            char *line = axctl_sprintf("decoration:shadow:color = %s\n", c);
            axctl_str_append(&out, line);
            free(line); free(c);
        }
    }

    if (cfg->animations) {
        if (cfg->animations->enabled)
            axctl_str_append(&out, axctl_sprintf("animations:enabled = %s\n",
                cfg->animations->enabled->value ? "true" : "false"));
    }

    if (cfg->layout)
        axctl_str_append(&out, axctl_sprintf("general:layout = %s\n", cfg->layout));

    return out;
}

char *hyprland_generate_keybinds(const axctl_keybind_t *binds, int count)
{
    if (!binds || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("# Keybinds (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_keybind_t *kb = &binds[i];
        if (!kb->enabled || !kb->key || !*kb->key) continue;

        /* Build modifier string */
        char *mods = axctl_strdup("");
        for (int j = 0; j < kb->modifier_count; j++) {
            if (j > 0) axctl_str_append(&mods, " ");
            axctl_str_append(&mods, kb->modifiers[j]);
        }

        char *line = axctl_sprintf("bind = %s, %s, %s, %s\n",
            *mods ? mods : "",
            kb->key,
            kb->dispatcher ? kb->dispatcher : "exec",
            kb->argument ? kb->argument : "");
        axctl_str_append(&out, line);
        free(line);
        free(mods);
    }

    return out;
}

char *hyprland_generate_window_rules(const axctl_window_rule_t *rules, int count)
{
    if (!rules || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("# Window Rules (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_window_rule_t *r = &rules[i];
        if (r->match && r->rule) {
            /* Legacy single-line rule */
            char *line = axctl_sprintf("windowrulev2 = %s, %s\n", r->rule, r->match);
            axctl_str_append(&out, line);
            free(line);
        } else if (r->match) {
            /* Block syntax */
            char *line = axctl_sprintf("windowrulev2 = ");
            axctl_str_append(&out, line); free(line);
            if (r->is_float && r->is_float->value)
                axctl_str_append(&out, "float, ");
            if (r->fullscreen && r->fullscreen->value)
                axctl_str_append(&out, "fullscreen, ");
            if (r->pin && r->pin->value)
                axctl_str_append(&out, "pin, ");
            if (r->no_blur && r->no_blur->value)
                axctl_str_append(&out, "noblur, ");
            if (r->no_shadow && r->no_shadow->value)
                axctl_str_append(&out, "noshadow, ");
            if (r->idle_inhibit && r->idle_inhibit->value)
                axctl_str_append(&out, "idleinhibit always, ");
            if (r->size) {
                char *s = axctl_sprintf("size %s, ", r->size);
                axctl_str_append(&out, s); free(s);
            }
            if (r->move) {
                char *s = axctl_sprintf("move %s, ", r->move);
                axctl_str_append(&out, s); free(s);
            }
            char *match = axctl_sprintf("%s\n", r->match);
            axctl_str_append(&out, match); free(match);
        }
    }
    return out;
}

char *hyprland_generate_layer_rules(const axctl_layer_rule_t *rules, int count)
{
    if (!rules || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("# Layer Rules (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_layer_rule_t *r = &rules[i];
        if (!r->namespace_str) continue;

        if (r->blur && r->blur->value) {
            char *line = axctl_sprintf("layerrule = blur, %s\n", r->namespace_str);
            axctl_str_append(&out, line); free(line);
        }
        if (r->no_anim && r->no_anim->value) {
            char *line = axctl_sprintf("layerrule = noanim, %s\n", r->namespace_str);
            axctl_str_append(&out, line); free(line);
        }
        if (r->no_shadow && r->no_shadow->value) {
            char *line = axctl_sprintf("layerrule = noshadow, %s\n", r->namespace_str);
            axctl_str_append(&out, line); free(line);
        }
        if (r->ignore_alpha && r->ignore_alpha->value) {
            if (r->ignore_alpha_value) {
                char *line = axctl_sprintf("layerrule = ignorealpha %.2f, %s\n",
                    r->ignore_alpha_value->value, r->namespace_str);
                axctl_str_append(&out, line); free(line);
            } else {
                char *line = axctl_sprintf("layerrule = ignorealpha, %s\n", r->namespace_str);
                axctl_str_append(&out, line); free(line);
            }
        }
    }
    return out;
}

char *hyprland_generate_startup(char **exec, int exec_count,
                                char **exec_once, int exec_once_count)
{
    char *out = axctl_strdup("# Startup (generated by axctl)\n");

    for (int i = 0; i < exec_count; i++) {
        char *line = axctl_sprintf("exec = %s\n", exec[i]);
        axctl_str_append(&out, line); free(line);
    }
    for (int i = 0; i < exec_once_count; i++) {
        char *line = axctl_sprintf("exec-once = %s\n", exec_once[i]);
        axctl_str_append(&out, line); free(line);
    }
    return out;
}

/* ── Lua syntax generators ──────────────────────────────────────────── */

char *hyprland_generate_appearance_lua(const axctl_appearance_t *cfg)
{
    if (!cfg) return axctl_strdup("");
    char *out = axctl_strdup("-- Appearance (generated by axctl)\n");

    if (cfg->gaps) {
        if (cfg->gaps->inner)
            axctl_str_append(&out, axctl_sprintf("hl.general.gaps_in = %d\n", cfg->gaps->inner->value));
        if (cfg->gaps->outer)
            axctl_str_append(&out, axctl_sprintf("hl.general.gaps_out = %d\n", cfg->gaps->outer->value));
    }

    if (cfg->border) {
        if (cfg->border->width)
            axctl_str_append(&out, axctl_sprintf("hl.general.border_size = %d\n", cfg->border->width->value));
        if (cfg->border->active_color) {
            char *c = axctl_hyprland_color(cfg->border->active_color);
            char *line = axctl_sprintf("hl.general[\"col.active_border\"] = \"%s\"\n", c);
            axctl_str_append(&out, line);
            free(line); free(c);
        }
        if (cfg->border->inactive_color) {
            char *c = axctl_hyprland_color(cfg->border->inactive_color);
            char *line = axctl_sprintf("hl.general[\"col.inactive_border\"] = \"%s\"\n", c);
            axctl_str_append(&out, line);
            free(line); free(c);
        }
        if (cfg->border->rounding)
            axctl_str_append(&out, axctl_sprintf("hl.decoration.rounding = %d\n", cfg->border->rounding->value));
    }

    if (cfg->blur) {
        if (cfg->blur->enabled)
            axctl_str_append(&out, axctl_sprintf("hl.decoration.blur.enabled = %s\n",
                cfg->blur->enabled->value ? "true" : "false"));
        if (cfg->blur->size)
            axctl_str_append(&out, axctl_sprintf("hl.decoration.blur.size = %d\n", cfg->blur->size->value));
        if (cfg->blur->passes)
            axctl_str_append(&out, axctl_sprintf("hl.decoration.blur.passes = %d\n", cfg->blur->passes->value));
    }

    if (cfg->animations && cfg->animations->enabled)
        axctl_str_append(&out, axctl_sprintf("hl.animations.enabled = %s\n",
            cfg->animations->enabled->value ? "true" : "false"));

    if (cfg->layout)
        axctl_str_append(&out, axctl_sprintf("hl.general.layout = \"%s\"\n", cfg->layout));

    return out;
}

char *hyprland_generate_keybinds_lua(const axctl_keybind_t *binds, int count)
{
    if (!binds || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("-- Keybinds (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_keybind_t *kb = &binds[i];
        if (!kb->enabled || !kb->key || !*kb->key) continue;

        char *mods = axctl_strdup("");
        for (int j = 0; j < kb->modifier_count; j++) {
            if (j > 0) axctl_str_append(&mods, " ");
            axctl_str_append(&mods, kb->modifiers[j]);
        }

        char *line = axctl_sprintf("hl.bind(\"%s\", \"%s\", \"%s\", \"%s\")\n",
            *mods ? mods : "",
            kb->key,
            kb->dispatcher ? kb->dispatcher : "exec",
            kb->argument ? kb->argument : "");
        axctl_str_append(&out, line);
        free(line);
        free(mods);
    }

    return out;
}

char *hyprland_generate_window_rules_lua(const axctl_window_rule_t *rules, int count)
{
    if (!rules || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("-- Window Rules (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_window_rule_t *r = &rules[i];
        if (r->match && r->rule) {
            char *line = axctl_sprintf("hl.windowrulev2(\"%s\", \"%s\")\n", r->rule, r->match);
            axctl_str_append(&out, line);
            free(line);
        }
    }
    return out;
}

char *hyprland_generate_layer_rules_lua(const axctl_layer_rule_t *rules, int count)
{
    if (!rules || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("-- Layer Rules (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_layer_rule_t *r = &rules[i];
        if (!r->namespace_str) continue;
        if (r->blur && r->blur->value) {
            char *line = axctl_sprintf("hl.layerrule(\"blur\", \"%s\")\n", r->namespace_str);
            axctl_str_append(&out, line); free(line);
        }
    }
    return out;
}

char *hyprland_generate_startup_lua(char **exec, int exec_count,
                                    char **exec_once, int exec_once_count)
{
    char *out = axctl_strdup("-- Startup (generated by axctl)\n");
    for (int i = 0; i < exec_count; i++) {
        char *line = axctl_sprintf("hl.exec(\"%s\")\n", exec[i]);
        axctl_str_append(&out, line); free(line);
    }
    for (int i = 0; i < exec_once_count; i++) {
        char *line = axctl_sprintf("hl.exec_once(\"%s\")\n", exec_once[i]);
        axctl_str_append(&out, line); free(line);
    }
    return out;
}
