/*
 * axctl - Niri config generator
 *
 * Generates KDL configuration syntax from universal config types.
 */

#include "ipc/niri/niri.h"
#include "ipc/config_types.h"
#include "ipc/colors.h"
#include "utils/strutil.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── KDL syntax generators ──────────────────────────────────────────── */

char *niri_generate_appearance(const axctl_appearance_t *cfg)
{
    if (!cfg) return axctl_strdup("");
    char *out = axctl_strdup("// Appearance (generated by axctl)\n");

    if (cfg->gaps && cfg->gaps->inner) {
        char *line = axctl_sprintf("layout {\n    gaps %d\n}\n", cfg->gaps->inner->value);
        axctl_str_append(&out, line); free(line);
    }

    if (cfg->border) {
        axctl_str_append(&out, "window-rule {\n    match is-active=true\n");
        if (cfg->border->width) {
            char *line = axctl_sprintf("    border { width %d; }\n", cfg->border->width->value);
            axctl_str_append(&out, line); free(line);
        }
        if (cfg->border->active_color) {
            char *c = axctl_first_color(cfg->border->active_color);
            char *line = axctl_sprintf("    border { active-color \"%s\"; }\n", c);
            axctl_str_append(&out, line); free(line); free(c);
        }
        if (cfg->border->inactive_color) {
            char *c = axctl_first_color(cfg->border->inactive_color);
            char *line = axctl_sprintf("    border { inactive-color \"%s\"; }\n", c);
            axctl_str_append(&out, line); free(line); free(c);
        }
        if (cfg->border->rounding) {
            char *line = axctl_sprintf("    corner-radius %d\n", cfg->border->rounding->value);
            axctl_str_append(&out, line); free(line);
        }
        axctl_str_append(&out, "}\n");
    }

    if (cfg->opacity) {
        if (cfg->opacity->active) {
            char *line = axctl_sprintf("window-rule {\n    match is-active=true\n    opacity %.2f\n}\n",
                cfg->opacity->active->value);
            axctl_str_append(&out, line); free(line);
        }
        if (cfg->opacity->inactive) {
            char *line = axctl_sprintf("window-rule {\n    match is-active=false\n    opacity %.2f\n}\n",
                cfg->opacity->inactive->value);
            axctl_str_append(&out, line); free(line);
        }
    }

    if (cfg->animations && cfg->animations->enabled) {
        if (!cfg->animations->enabled->value)
            axctl_str_append(&out, "animations {\n    off\n}\n");
    }

    return out;
}

char *niri_generate_keybinds(const axctl_keybind_t *binds, int count)
{
    if (!binds || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("// Keybinds (generated by axctl)\nbinds {\n");

    for (int i = 0; i < count; i++) {
        const axctl_keybind_t *kb = &binds[i];
        if (!kb->enabled || !kb->key || !*kb->key) continue;

        /* Build modifier string */
        char *mods = axctl_strdup("");
        for (int j = 0; j < kb->modifier_count; j++) {
            axctl_str_append(&mods, kb->modifiers[j]);
            axctl_str_append(&mods, "+");
        }

        char *line = axctl_sprintf("    %s%s { %s \"%s\"; }\n",
            mods,
            kb->key,
            kb->dispatcher ? kb->dispatcher : "spawn",
            kb->argument ? kb->argument : "");
        axctl_str_append(&out, line);
        free(line);
        free(mods);
    }

    axctl_str_append(&out, "}\n");
    return out;
}

char *niri_generate_window_rules(const axctl_window_rule_t *rules, int count)
{
    if (!rules || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("// Window Rules (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_window_rule_t *r = &rules[i];
        if (!r->match) continue;

        char *line = axctl_sprintf("window-rule {\n    match %s\n", r->match);
        axctl_str_append(&out, line); free(line);

        if (r->is_float && r->is_float->value)
            axctl_str_append(&out, "    open-floating true\n");
        if (r->fullscreen && r->fullscreen->value)
            axctl_str_append(&out, "    open-fullscreen true\n");
        if (r->no_shadow && r->no_shadow->value)
            axctl_str_append(&out, "    draw-border-with-background false\n");
        if (r->size) {
            char *s = axctl_sprintf("    default-column-width { fixed %s; }\n", r->size);
            axctl_str_append(&out, s); free(s);
        }

        axctl_str_append(&out, "}\n");
    }
    return out;
}

char *niri_generate_layer_rules(const axctl_layer_rule_t *rules, int count)
{
    if (!rules || count <= 0) return axctl_strdup("");
    char *out = axctl_strdup("// Layer Rules (generated by axctl)\n");

    for (int i = 0; i < count; i++) {
        const axctl_layer_rule_t *r = &rules[i];
        if (!r->namespace_str) continue;

        char *line = axctl_sprintf("layer-rule {\n    match namespace=\"%s\"\n", r->namespace_str);
        axctl_str_append(&out, line); free(line);

        if (r->blur && r->blur->value)
            axctl_str_append(&out, "    blur { enable true; }\n");
        if (r->no_shadow && r->no_shadow->value)
            axctl_str_append(&out, "    shadow { enable false; }\n");

        axctl_str_append(&out, "}\n");
    }
    return out;
}

char *niri_generate_startup(char **exec, int exec_count,
                            char **exec_once, int exec_once_count)
{
    char *out = axctl_strdup("// Startup (generated by axctl)\n");
    for (int i = 0; i < exec_count; i++) {
        char *line = axctl_sprintf("spawn-at-startup \"%s\"\n", exec[i]);
        axctl_str_append(&out, line); free(line);
    }
    for (int i = 0; i < exec_once_count; i++) {
        char *line = axctl_sprintf("spawn-at-startup \"%s\"\n", exec_once[i]);
        axctl_str_append(&out, line); free(line);
    }
    return out;
}
